# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotifyWatch' do
      pod 'Socket.IO-Client-Swift', '~> 15.2.0'
end

target 'NotifyWatchApp Extension' do
      pod 'Socket.IO-Client-Swift', '~> 15.2.0'
end
